const cols = [
	{
		value: "Month",
		type: "select",
		data: [
			"Select month need to check",
			Array.from({ length: 12 }, (_, i) => i + 1),
		].flat(),
		// or false, depending on your default preference
	},
	{ value: "Age", type: "input", data: [] },
	{
		value: "Occupation",
		type: "select",
		data: [
			"Select your occupation",
			"Accountant",
			"Architect",
			"Developer",
			"Doctor",
			"Engineer",
			"Entrepreneur",
			"Journalist",
			"Lawyer",
			"Manager",
			"Mechanic",
			"Media_Manager",
			"Musician",
			"Scientist",
			"Teacher",
			"Writer",
		],
	},
	{ value: "Annual Income", type: "input", data: [] },
	{ value: "Monthly Inhance Salary", type: "input", data: [] },
	{ value: "Num Bank Accounts", type: "input", data: [] },
	{ value: "Num Credit Cards", type: "input", data: [] },
	{
		value: "Interest Rate",
		type: "input",
		data: [],
		nextHidden: "Num of Loan",
	},
	{ value: "Delay From Due Date", type: "input", data: [] },
	{ value: "Num Of Delayed Payment", type: "input", data: [] },
	{ value: "Changed Credit Limit", type: "input", data: [] },
	{ value: "Num Credit Inquiries", type: "input", data: [] },
	{
		value: "Credit Mix",
		type: "select",
		data: ["Select your credit mix", "Bad", "Good", "Standard"],
	},
	{ value: "Outstanding Debt", type: "input", data: [] },
	{ value: "Credit Utilization Ratio", type: "input", data: [] },
	{ value: "Credit History Age", type: "input", data: [] },
	{
		value: "Payment of Min Amount",
		type: "select",
		data: ["Select your payment of min amount", "NM", "No", "Yes"],
	},
	{ value: "Total EMI Per Month", type: "input", data: [] },
	{ value: "Amount Invested Monthly", type: "input", data: [] },
	{
		value: "Payment Behaviour",
		type: "select",
		data: [
			"Select your payment behaviour",
			"High spend Large value payments",
			"High spend Medium value payments",
			"High spend Small value payments",
			"Low spend Large value payments",
			"Low spend Medium value payments",
			"Low spend Small value payments",
		],
	},
	{
		value: "Monthly Balance",
		type: "input",
		data: [],
		nextHidden: "EMI Income Ratio",
	},
];

export default cols;
